fixtures:
  repositories:
    stdlib:
      repo: 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref: '4.1.0'
    vcsrepo:
      repo: 'git://github.com/puppetlabs/puppetlabs-vcsrepo.git'
      ref: '1.3.2'
  symlinks:
    pe_report_slack: "#{source_dir}"
