language: ruby
bundler_args: "--without system_tests"
branches:
  only:
  - master
script: bundle exec rake validate && bundle exec rake lint && bundle exec rake spec
  SPEC_OPTS='--format documentation' && bundle exec rake metadata_lint
env:
  global:
  - secure: wq529Tqk4mcKNybKeIuEnysbobfO/XUcSoDHUMLtCkX6NKkwQv+jS7RbRqnW46NneYLcc6F5pLm9Mn8Yb3RwMe/jGnxGGMTw7vWu3GO5QNrY+ELkbU1AqHw4nPsdZONhpHBt/N0hOrhO6spD9p5DyJippG/WJa9k7rFI8ZtL1RCl1BHQiOEVxxXZImti+vFowyi9YwFUfJ6mx72h5hcsG0ipxTF9SjSAMwcy9qyogL6abYzHaZODuNP0qBWBTlKx5VqyyhwzRFCHkr3MYQJu1TQ5+Zgx8EBRpSq95Ez4Y3Sc0Hqi3+nLcBjBuhUNQLrm5xzUwY1GLMNPy4s3j6aj90BSuxzYuzr8XDMnvM/y2BItQOR3vF749XCK2HtvdZELWVVSiIwoGnFFBChj1KjcOch27n7lIZCk1HfGuq/wKerfhjulDbCU8wKVeSderL+20O1ltEGHYsZLjADOJl/wgTQcW0AJYfloVMfglyaR0pKggBWsYfUSG52I0WatHOVbuxbBzY/Qf92g9EHNXrtQda6C1qoI8rlf2tEC+DlRMzZEYJZM9qIVGGANyiTVg6AVQh6oFFCNgY7GvPFdB21i8XGFIlwSJjwFqCc9xPeely7jSE4RQyw1kU5FLjVviLbviP7ac5QCxW45SROSNQ30qqt7HD6m7TCEwWlPBetOgwU=
  - secure: EjbPQlrAgznsxGiclMORBdo1GPAaLHv0YVPznJqEKZD/M1uaGQXjDUgQfH2hVqMwwxo4WzUUsaWbI+J/AgN555GHYwyT9mRJj9Nxt2+kcDGtwNACawpjQz/0DvAt7u++bO9qeiPAoeK/ktLjicEtJU/QLSKGXuYJgLv6KDhsXhjJs9x7LXaHxbua7PAq5p0Ws8T13cOlv2OvTkVHcHyPjDXAgJE/M6+zKSqIbwtWINK1l3iOfYTFMJ7iYPLrFAPO7ZLref/ShLgCpjr++ApoRiuVw/1a6DcU+ATDyzDj7e1AspxXqctRZ+fzDyfpmQxHqZNTEvy580/KrymxgZzKkIHpQnaUeqooU71YAa8A6/D6cpcoudkym7iNWgELTucnA5SzsMBuaIEEI8//h24VkUA/uRpHlO5w0+99lk4nWjcTfqITCevEQJSH3aIq05pzyaOii2v8wKyfS8aunbKK/Eok+uNZVzoaXKmFpnoBI+RdafxFiE53ak2pIL9Gr6aysqrVyp31mu333yIo9s5cH04dq3ZKc/c1p2upMqLOKGRw88/c0lpLpOqgRY/GhOVG4eTVdDcUtZe1NrfU46wpsZvy3SarpFOQ7ibQl5hW4QuqH1J2uCOG0bChWtrsEcRqD3LQ1bCENqQPWBmpjcd2eEQ8dxhv722k0vaXElJ6zZg=
  - secure: LxI4UqKFmXS1f699ZGAT3EImvsRKYfkhvzW0PO/KJcm0pCVTcMVvyUCVTvkHSiTVkec+SonzdU2DsTOYfTpbjmhHT6IPseSoFhzcx0RrI7Wf8x07u0zozJmuRgScmb5NU6TZiki6U+xyXThDZjQJZ0vLLSYB4UIN4T+ONtseBW9ZpP/c3JUeTKxFHIm/F51zoeKY/3/S+bR8rUTDQjUd1q17NoODDJEOiB0QMdJPr39AI9XX20GgJG3dq5DbLsST4pbN+caQahuB+PwsllhQfdNWR6Q1G17ZPv9Vb3pGpNSXw+dHqXn2wcrZnLlkpNgS8hsLlpRKRMXxmMpPBXu+9DNCp5GlWYEsqRvucc7VMjua86CzNjfae9JUko6shommM0eeU6Zj8bLLhcRzQMOwbAUuKWlkGieE4i9F26sL0HS9pjYlth5SqD7ql9jgTC2a3zfW2aCStr7eMLBSVU5EqDrfhFmHvtlW5OC8ZtqaFn8+UjO1QSUBYSZ/yIvrYEPz9oSKQubakgMfgpUk0fdkAoBOqHjQemAoMQN6v4srbbPjxMSYZSaOejad71Xd7/jrf1BLl/i1nAfJ3TfFU/cWy7IGRH/+F+VEIZRUIanlSx5CXEOUt3cPq+x+zLsNrKpMgekwVSW9OdybZWqHQi8M7+wg7f4Cjpm8qLwpqzpWCys=
  - BLACKSMITH_FORGE_URL=https://forgeapi.puppetlabs.com
matrix:
  include:
  - rvm: 2.1.8
    env: PUPPET_VERSION="~> 4.4.0"
  - rvm: 2.1.8
    env: PUPPET_VERSION="~> 4.3.0" FACTER_VERSION="~> 2.4.0"
  - rvm: 2.1.6
    env: PUPPET_VERSION="~> 4.2.0" FACTER_VERSION="~> 2.4.0"
notifications:
  email: nicolas@corrarello.com
  slack:
    secure: NamGNMqfEDNTLZ1seSFO477QJi3S+nVftNRg4HjbVKO6BDAXP0kM3kQ0DJgoqn1ZCyN7RL9OZoQLK4pcCGIeQNkJfRQWoK2/02bxVDcDV7Hp5nPOQO0PFBhsT5i84tmJMi1Le+jpTPr2T/rDKgeDdSqVCqaWfFNoB0f/55ti2WZGC0hTJIW3//Ml6fHJlv12dqxQ2aGJJvYDT8CyUHQw1w70mHyIF7HISDuKfSBMoA4yd6AAclt5LsATrIehcp464KrNo5a0OXTeBqnIBnSQ1AypdEbbBdyq5Qw3/ieq4M5mv+Rtcqo9E1ElmDcSMqmxxKi9Q9AIVCEfTdtv0JgAvlj70J0UvnujtyiGkBBF4LmWAbRQwegiq/IbpaWPcYVfHfo9yJQz9oLF+LPzlkezaPiQl1W3nwh4NjpIOL5JeOEtJZjOWgIQZVfnivpvGIuooniikovBhdgiME0bhFE4B7JSv3Y/L8TlNNcDsY/swqL6KKwH/uco1vVwpCGWkVulKRdRf7nguuV3PxzJDWEx6Xu4VmMdWnbgwQacNEG9hzAQ2bO3oyqAFqwS5G1BRheB6mu6096w2Tv81PQ8iPR3BF/4QyciCrgNm2c3WGDAjjKG8wbQac1gpMX6RnB3hFr0G5i6kR0Bf/+ifTpV2nzFzk6khcp3sS4eOJm0BnQlxtc=
after_success:
- curl -o /tmp/travis-automerge https://raw.githubusercontent.com/ncorrare/travis-scripts/master/aftersuccessforge.sh
- chmod a+x /tmp/travis-automerge
- "/tmp/travis-automerge"
